### ISSUE TITLE
Can I use your lab website as a template to build my lab website

### ISSUE THREAD

**Issue by Xiaojieqiu** [ato-neulab/Lab-Website#4]
Hi @chrooks, thanks for your amazing work on this pleasing looking website. I am curious about whether it is okay for us to use the source code of your website as a template to build my own lab's website? My lab's research direction is in genetics, especially single cell and spatial genomics with a focus on the heart: https://scholar.google.com/citations?user=XlMd8TAAAAAJ&hl=en

**Comment by chrooks** [comment]
Hi Xiaojie,

Of course! Please do let me know if you have any questions!

Well wishes,
Chris

From: Xiaojie Qiu ***@***.***>
Sent: Friday, December 29, 2023 02:41 PM
To: ato-neulab/Lab-Website ***@***.***>
Cc: Christopher Brooks ***@***.***>; Mention ***@***.***>
Subject: [ato-neulab/Lab-Website] Can I use your lab website as a template to build my lab website (Issue #4)


Hi @chrooks<https://github.com/chrooks>, thanks for your amazing work on this pleasing looking website. I am curious whether it is okay for us to use the source code of your website as a template to build my own lab's website? My lab's research direction is in genetics, especially single cell and spatial genomics with a focus on the heart: https://scholar.google.com/citations?user=XlMd8TAAAAAJ&hl=en

-

**Comment by Xiaojieqiu** [comment]
Hi Chris, 

Happy new year! Thanks for offering me the opportunity to use your code. Please see my updated code based on your template: https://github.com/aristoteleo/qiu_lab_website and the resultant lab website here: https://www.devo-evo.com/

So far everything works well for me -- and I really appreciate your amazing work on designing the website. If I may have any questions, I will let you know!  

Thanks,
Xiaojie
